### ISSUE TITLE
Calculate Mobility Activity Levels 

### ISSUE THREAD

**Issue by g4brielvs** [datapartnership/myanmar-economic-monitor#13]
As an exploratory analysis, the project team would analyze changes in activity levels in select border towns as well as zones in Yangon by OpenStreetMap land use (residential, commercial, industrial) using mobile location data. As a second step, the project team would prepare a trend line chart with these activity levels and overlay trends in nighttime lights and regional GDP to see the extent to which the three data streams correlate. 

Here's the [link to Myanmar's border town coordinates](https://worldbankgroup.sharepoint.com/:f:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Projects/Data%20Lab/Myanmar%20Economic%20Monitor/Data/Points%20of%20Interest?csf=1&web=1&e=27giMH).

```[tasklist]
### Tasks
- [x] Calculate Mobility Activity Levels in select zones
- [ ] Overlay trends in nighttime lights
```

**Comment by jfulponi** [comment]
First Pull Request created with indicators, methodology and visualisations -> #15.
